"""Promote styles that several modules repeat into shared components.

Two steps, so every shared name is chosen deliberately:

    python tools/promote_components.py --plan plan.json [--min 2]
    python tools/promote_components.py --apply plan.json

--plan lists every declaration block that at least --min modules define under
their own class names and that is not shared yet. Each entry carries the
declarations, the modules and class names that use it, and a suggested name
(the most widely used one). Edit "name" to the shared name wanted, or set it to
"" to leave that block alone.

Only two kinds of block are candidates:
  * structure and typography whose colours are theme tokens, never literals
  * utility and palette classes (u-*, text-blue-900), which keep a utility name

Blocks with literal colours are colour variants, and blocks positioning or
sizing with percentages are chart data; both are handled differently. Blocks
with quoted values are skipped, because blocks are compared case-insensitively.

--apply checks every chosen name and writes nothing unless all pass. A name is
refused when it is not a plain lowercase hyphenated name, is chosen twice, or
is unsafe to make global:
  * wherever a module defines it as a plain rule it must mean exactly this
    block, defined once
  * every module whose page mentions it must define it identically, so no
    element anywhere picks up rules it did not have
  * no shared stylesheet, layout, component or non-module page may use it

components.css only ever grows. consolidate_css.py --apply then folds each
module's copy into the shared class.
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

from consolidate_css import MODULE_CSS, PAGES, read, word, write

ROOT = Path(__file__).resolve().parent.parent
STYLES = ROOT / 'src' / 'styles'
COMPONENTS = STYLES / 'components.css'
GLOBAL_SHEETS = ['shared.css', 'chrome.css', 'home.css', 'about.css', 'fonts.css', 'icons-base.css']
NON_MODULE_SOURCES = ([ROOT / 'src' / 'pages' / 'index.astro', ROOT / 'src' / 'pages' / 'about.astro',
                       PAGES / 'index.astro']
                      + sorted((ROOT / 'src' / 'pages' / 'topics').glob('*.astro'))
                      + sorted((ROOT / 'src' / 'components').glob('*.astro'))
                      + sorted((ROOT / 'src' / 'layouts').glob('*.astro')))

UTILITY = re.compile(r'^(u-[\w-]+|(text|bg|border)-[a-z]+-\d+)$')
SINGLE = re.compile(r'^\.([a-z][\w-]*)$')
NAME = re.compile(r'^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$')
LITERAL_COLOUR = re.compile(r'#[0-9a-f]{3,8}\b|\brgba?\(|\bhsla?\(', re.I)
DATA_GEOMETRY = {'width', 'height', 'left', 'right', 'top', 'bottom', 'flex'}

HEADER = """/* ============================================================
   Shared components.

   Styles that several modules define identically, each defined once here.
   Generated by tools/promote_components.py, which only ever adds to this
   file; module copies are folded in by tools/consolidate_css.py.
   ============================================================ */
"""


def top_rules(css: str) -> list[tuple[str, list[tuple[str, str]]]]:
    """Top-level rules only (nothing inside @media), declarations in source order."""
    css = re.sub(r'/\*[\s\S]*?\*/', lambda m: ' ' * len(m.group(0)), css)
    out: list[tuple[str, list[tuple[str, str]]]] = []
    stack: list[tuple[int, int]] = []
    start = 0
    for t in re.finditer(r'[{}]', css):
        if t.group() == '{':
            stack.append((start, t.start()))
            start = t.end()
            continue
        s0, s1 = stack.pop()
        selector = re.sub(r'\s+', ' ', css[s0:s1]).strip()
        body = css[s1 + 1:t.start()]
        if not stack and not selector.startswith('@') and '{' not in body:
            decls = []
            for d in body.split(';'):
                if ':' in d:
                    k, _, v = d.partition(':')
                    decls.append((k.strip(), re.sub(r'\s+', ' ', v).strip()))
            if decls:
                out.append((selector, decls))
        start = t.end()
    return out


def key(decls) -> tuple:
    return tuple(sorted((k.lower(), v.lower()) for k, v in decls))


def scan():
    """Everything both steps need about the current stylesheets and pages."""
    taken: set[str] = set()
    for name in GLOBAL_SHEETS:
        sheet = STYLES / name
        if sheet.exists():
            taken.update(re.findall(r'\.([A-Za-z_][\w-]*)', read(sheet)))
    for sheet in sorted((STYLES / 'icons').glob('*.css')):
        taken.update(re.findall(r'\.([A-Za-z_][\w-]*)', read(sheet)))
    for source in NON_MODULE_SOURCES:
        if source.exists():
            for attr in re.findall(r'\bclass="([^"]*)"', read(source)):
                taken.update(attr.split())

    existing: dict[str, list[tuple[str, str]]] = {}
    if COMPONENTS.exists():
        for selector, decls in top_rules(read(COMPONENTS)):
            m = SINGLE.match(selector)
            if m:
                existing[m.group(1)] = decls

    definitions: dict[str, dict[str, list[tuple]]] = {}
    pages: dict[str, str] = {}
    clusters: dict[tuple, list[tuple[str, str]]] = defaultdict(list)
    source_decls: dict[tuple, list[tuple[str, str]]] = {}
    for css_file in sorted(MODULE_CSS.glob('*.css')):
        slug = css_file.stem
        page = PAGES / f'{slug}.astro'
        if not page.exists():
            continue
        pages[slug] = read(page)
        names: dict[str, list[tuple]] = defaultdict(list)
        for selector, decls in top_rules(read(css_file)):
            m = SINGLE.match(selector)
            if not m:
                continue
            k = key(decls)
            names[m.group(1)].append(k)
            clusters[k].append((slug, m.group(1)))
            source_decls.setdefault(k, decls)
        definitions[slug] = names
    return taken, existing, definitions, pages, clusters, source_decls


def unsafe(name, k, taken, existing, definitions, pages) -> str | None:
    if name in taken or name in existing:
        return 'already shared or used outside the modules'
    for slug, names in definitions.items():
        if name in names:
            if names[name] != [k]:
                return f'means something else in {slug}'
        elif re.search(word(name), pages[slug]):
            return f'used without this rule in {slug}'
    return None


def plan(path: Path, minimum: int) -> int:
    taken, existing, definitions, pages, clusters, source_decls = scan()
    shared_keys = {key(d) for d in existing.values()}
    entries, skipped = [], defaultdict(int)
    for k, members in sorted(clusters.items(), key=lambda kv: (-len({s for s, _ in kv[1]}), kv[0])):
        modules = sorted({slug for slug, _ in members})
        if len(modules) < minimum:
            continue
        names = sorted({n for _, n in members})
        utility_only = all(UTILITY.match(n) for n in names)
        if k in shared_keys:
            skipped['already shared'] += 1
            continue
        if any('"' in v or "'" in v for _, v in k):
            skipped['quoted value'] += 1
            continue
        if not utility_only and any(LITERAL_COLOUR.search(v) for _, v in k):
            skipped['literal colours (colour variant)'] += 1
            continue
        if not utility_only and any(p in DATA_GEOMETRY and '%' in v for p, v in k):
            skipped['percentage geometry (chart data)'] += 1
            continue
        candidates = [n for n in names if bool(UTILITY.match(n)) == utility_only]
        candidates.sort(key=lambda n: (-len({s for s, m in members if m == n}), len(n), n))
        entries.append({
            'name': candidates[0],
            'kind': 'utility' if utility_only else 'component',
            'declarations': [f'{p}: {v}' for p, v in source_decls[k]],
            'modules': len(modules),
            'members': sorted(f'{s}:{n}' for s, n in members),
        })
    path.write_text(json.dumps(entries, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
    kinds = defaultdict(int)
    for e in entries:
        kinds[e['kind']] += 1
    print(f'candidates written : {len(entries)} ({", ".join(f"{k} {n}" for k, n in kinds.items())})')
    print(f'module rules they cover: {sum(len(e["members"]) for e in entries)}')
    print('skipped            : ' + (', '.join(f'{r} x{n}' for r, n in skipped.items()) or 'none'))
    print(f'plan: {path}')
    return 0


def apply(path: Path) -> int:
    taken, existing, definitions, pages, clusters, source_decls = scan()
    entries = json.loads(path.read_text(encoding='utf-8'))
    chosen: dict[str, list[tuple[str, str]]] = {}
    refusals: list[str] = []
    for e in entries:
        name = e['name']
        if not name:
            continue
        decls = [tuple(s.split(': ', 1)) for s in e['declarations']]
        k = key(decls)
        if k not in clusters:
            refusals.append(f'{name}: block no longer present in any module')
            continue
        utility = bool(UTILITY.match(name))
        if not NAME.match(name) or (not utility and re.search(r'-\d+$', name)) or len(name) > 40:
            refusals.append(f'{name}: not a plain readable name')
            continue
        if utility != (e['kind'] == 'utility'):
            refusals.append(f'{name}: a {e["kind"]} block needs a {e["kind"]} name')
            continue
        if name in chosen:
            refusals.append(f'{name}: chosen twice')
            continue
        why = unsafe(name, k, taken, existing, definitions, pages)
        if why:
            refusals.append(f'{name}: {why}')
            continue
        chosen[name] = source_decls[k]

    print(f'names checked : {sum(1 for e in entries if e["name"])}')
    print(f'refused       : {len(refusals)}')
    for r in refusals:
        print('   ' + r)
    if refusals:
        return 1

    merged = {**existing, **chosen}
    components = sorted(n for n in merged if not UTILITY.match(n))
    utilities = sorted(n for n in merged if UTILITY.match(n))

    def render(name: str) -> str:
        return f'.{name} {{\n' + ''.join(f'  {p}: {v};\n' for p, v in merged[name]) + '}\n'

    text = HEADER + '\n/* ---- components ---- */\n\n' + '\n'.join(render(n) for n in components)
    if utilities:
        text += '\n/* ---- utilities and palette ---- */\n\n' + '\n'.join(render(n) for n in utilities)
    write(COMPONENTS, text)
    print(f'wrote {COMPONENTS.relative_to(ROOT).as_posix()}: +{len(chosen)} '
          f'({len(components)} components, {len(utilities)} utilities in total)')
    return 0


def main(argv: list[str]) -> int:
    minimum = int(argv[argv.index('--min') + 1]) if '--min' in argv else 2
    if '--plan' in argv:
        return plan(Path(argv[argv.index('--plan') + 1]), minimum)
    if '--apply' in argv:
        return apply(Path(argv[argv.index('--apply') + 1]))
    print(__doc__)
    return 2


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
